# Generated by Django 3.2.1 on 2022-04-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('powerscore', models.BigIntegerField(default=0)),
                ('gold_donation', models.IntegerField(default=0)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clan')),
            ],
        ),
    ]
