# Generated by Django 3.2.1 on 2022-04-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='total_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clan',
            name='total_powerscore',
            field=models.BigIntegerField(default=0),
        ),
    ]
