# Generated by Django 3.2.1 on 2022-04-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220411_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='gold_donation',
            field=models.IntegerField(default=0),
        ),
    ]
