# Generated by Django 3.2.1 on 2022-04-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_clan_gold_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='total_members',
            field=models.IntegerField(default=0),
        ),
    ]
