# Generated by Django 3.2.1 on 2022-04-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_clan_total_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='powerscore',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='total_powerscore',
        ),
        migrations.AddField(
            model_name='character',
            name='gold_debt',
            field=models.IntegerField(default=0),
        ),
    ]
