# Generated by Django 3.2.1 on 2022-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220411_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='advanced_gold',
            field=models.IntegerField(default=0),
        ),
    ]
