# Generated by Django 3.2.1 on 2022-04-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_character_advanced_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.clan'),
        ),
    ]
