# Generated by Django 3.2.1 on 2022-04-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_character_clan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='total_gold',
        ),
    ]
